# umami-update.yml
---
- name: Update Umami service
  hosts: vultr_servers
  become: true

  tasks:
    - name: Pull new Umami Docker images
      ansible.builtin.shell: docker-compose pull
      args:
        chdir: /etc/docker/umami/

    - name: Recreate Umami containers
      ansible.builtin.shell: docker-compose up --force-recreate -d
      args:
        chdir: /etc/docker/umami/
